[mongodb]
localhost

[redis]
localhost

[mysql]
localhost

[rabbitmq]
localhost

[catalogue]
catalogue.manibhargavi2225.online

[cart]
cart.manibhargavi2225.online

[user]
user.manibhargavi2225.online

[shipping]
shipping.manibhargavi2225.online

[payment]
payment.manibhargavi2225.online

[frontend]
frontend.manibhargavi2225.online

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory

 